version: '3.7'

services:
  # laravel-app:
  #   platform: linux/x86_64
  #   image: mrfzy00/crud_laravel_api-sre-test-app
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - laravel-app
  #   environment:
  #     - DB_DATABASE
  #     - DB_PORT
  #     - DB_USERNAME
  #     - DB_PASSWORD

  db-server:
    platform: linux/x86_64
    image: mysql:5.7-oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=db_laravel
      - MYSQL_ROOT_PASSWORD=Ch4ng3me!@
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - laravel-app

  cache-server:
    platform: linux/x86_64
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass Ch4ng3me!@
    volumes:
      - cache:/data
    networks:
      - laravel-app
  
networks:
  laravel-app:

volumes:
  cache:
    driver: local