laravel-minikube:
replicaCount: 1
image:
  repository: ghcr.io/rizkyfaza20/api-laravel-k8s-dev
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: laravel-app
  type: ClusterIP
  port: 8000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50


ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: chart-example.local
    paths: ["/"]
  tls: []

database:
  mysql:
    connection: mysql
    port: 3306
    username: laraveluser
    password: "Ch4ng3me!@"
    database: db_laravel
    rootPassword: "Ch4ng3me!@"
